レスポンスクラスを関数で実装したものを入れました。
kohkubo/webserv pull request #109
Opened 2022-04-18 07:00 UTC by ryojiroakiyama

ディレクトリ構成が汚くなるかと思い, include, srcsディレクトリにそれぞれresponseというディレクトリを作りました。
responseディレクトリに元のレスポンスクラスとそれを関数で実装したものどちらも入れています。
responseクラスはいらなかったら消して問題ないです。

2022-04-18 07:36 UTC, kohkubo commented
必要だったらまた書けばいいので、クラスは消していいと思います。

2022-04-18 07:38 UTC, kohkubo requested changes
必要だったらまた書けばいい、もしくはgitで戻せばいいので、クラスは消していいと思います。
見にくくなるので、大きな変更であっても、そこらへんは大胆にやっちゃっていいと思います。
簡単に戻せるのがgithubの良いところです。

2022-04-18 07:58 UTC, ryojiroakiyama commented
> 必要だったらまた書けばいい、もしくはgitで戻せばいいので、クラスは消していいと思います。 見にくくなるので、大きな変更であっても、そこらへんは大胆にやっちゃっていいと思います。 簡単に戻せるのがgithubの良いところです。

了解です！そうします！

2022-04-18 09:09 UTC, kohkubo commented
messageというディレクティブ以外に適切な命名がありそう。httpとかどうだろう?

2022-04-18 09:22 UTC, kohkubo commented
関数の位置が変だったので、プルリク投げました

2022-04-18 09:30 UTC, kohkubo commented on srcs/server.cpp
> +      std::string  request_message = read_request(accfd);
ここを関数にまとめてほしいです

2022-04-19 01:58 UTC, nakamo326 approved these changes
確認しました。

2022-04-19 01:58 UTC, nakamo326 commented on srcs/http/response.cpp
> +std::string response_message(message_type &response) {
関数の命名が名詞的なので誤解を生むかもしれません。
（”レスポンスメッセージ”を作る関数として命名したと思うのですが、”メッセージを応答する”関数としてとらえることもできてしまう。）
generate_response, get_response_messageのような動詞＋目的語の命名にするとこういった誤解を避けることができると思います。

2022-04-19 01:58 UTC, nakamo326 commented on srcs/http/http.cpp
> +void http(int accfd) {
この関数名についてもresponse.cppでのコメントと同様に、関数名を動詞＋目的語に直したほうが分かりやすいと思います。
e.g.) handle_http_request

2022-04-19 03:33 UTC, kohkubo approved these changes
一旦 approveします。
指摘して、直してもらってを繰り返すと時間がかかりそうなので、命名とか、関数の分け方とか、今週、僕がリファクタリングして提案を投げると思います。それを参考にどのような形で書くのがよいのか、話し合いましょう。

テストなどちゃんとかけていて良いと思いました。

2022-04-19 03:33 UTC, kohkubo commented on srcs/http/response.cpp
> +std::string response_message(message_type &response) {
僕ならこう書きますね。strlenみたいに名詞で書くのはわかりやすくなる場合もあるから、良いと思うけどプロトコルの名詞であることを明示しないとnakamotoさんの言うように、わかりにくくなると思う。

```c
// clang-format off
std::string http_requests_message(message_type &response) {
  return \
    http_requests_startline() + \
    http_requests_headers() + \
    http_empty_line() + \
    http_requests_body();
}
// clang-format on
```

2022-04-19 03:33 UTC, kohkubo commented on srcs/http/response.cpp
> +std::string response_message(message_type &response) {
field_messageってどこから来ていますか?
リファレンスにはそういう言葉が見つからなかった
https://developer.mozilla.org/ja/docs/Web/HTTP

2022-04-19 03:33 UTC, kohkubo commented on srcs/http/response.cpp
> +std::string response_message(message_type &response) {
![HTTPMsgStructure2-1](https://user-images.githubusercontent.com/69159167/163913810-0a17de66-8938-4aa7-8ac3-cb707320f6ec.png)

2022-04-19 13:06 UTC, closed without merging