multipart/form-dataを
kohkubo/webserv pull request #413
Opened 2022-06-08 10:49 UTC by ryojiroakiyama

2022-06-09 14:40 UTC, ryojiroakiyama commented
クラスに変えます。
理由
- まとめる
- multipart/form-dataでも流用したい

2022-06-10 06:48 UTC, kohkubo requested changes

2022-06-10 06:48 UTC, kohkubo commented on srcs/http/request/RequestInfo_header.cpp
> +    content_type_ = __parse_multi_field(itr->second);
mulit_fieldはRFCで呼ばれている名前ですか？
この構造体でメインの情報はcontent_typeだと思うのでそのままcontent_typeか、content_type_field等、content_typeが入っている方がわかりやすいかと思いましたがどうでしょうか。

2022-06-10 06:48 UTC, kohkubo commented on srcs/http/request/RequestInfo_header.cpp
> +std::string RequestInfo::__trim_double_quote(std::string str) {
__trim_double_quoteと__trim_optional_whitespaceを抽象化して、trimする文字列を渡す関数として一つにできないでしょうか。

2022-06-10 09:05 UTC, ryojiroakiyama commented on srcs/http/request/RequestInfo_header.cpp
> +    content_type_ = __parse_multi_field(itr->second);
この関数は";"を含む文字列からMultiField構造体に値を格納して返すという機能が主で, 
他でも使用するので, 名前を__parse_multi_fieldにしています。
構造体のメソッドにした方がいいですかね。

2022-06-10 09:06 UTC, ryojiroakiyama commented on srcs/http/request/RequestInfo_header.cpp
> +std::string RequestInfo::__trim_double_quote(std::string str) {
できそうです！やってみます！

2022-06-10 09:18 UTC, kohkubo commented on srcs/http/request/RequestInfo_header.cpp
> +    content_type_ = __parse_multi_field(itr->second);
MultiField構造体の名前の話です。

MultiField構造体は、Content-typeのデータを格納する以外に使われるタイミングがあるのでしょうか?
現状、headerでもbodyでもContent-typeに使われるのであれば、構造体の名前自体をContent-type構造体という名前で良いのでは？と感じました！

2022-06-10 09:20 UTC, kohkubo commented on srcs/http/request/RequestInfo_header.cpp
> +    content_type_ = __parse_multi_field(itr->second);
関数は現状の場所の方が、見やすいように感じています！

2022-06-10 09:22 UTC, kohkubo commented on srcs/http/request/RequestInfo_header.cpp
> +    content_type_ = __parse_multi_field(itr->second);
言葉下手ですみません。
なるほど！
"ContentInfo"でどうでしょうか

2022-06-10 09:23 UTC, ryojiroakiyama commented on srcs/http/request/RequestInfo_header.cpp
> +    content_type_ = __parse_multi_field(itr->second);
良さそうです！そうします！

2022-06-10 11:12 UTC, ryojiroakiyama commented on srcs/http/request/RequestInfo_header.cpp
> +std::string RequestInfo::__trim_double_quote(std::string str) {
やったこと
- __trim_optional_whitespaceを__erase_side_charsという引数によってトリムする文字列を指定するものに変更
- __trim_double_quoteを__cutout_prameter_valueという目的に沿った名前に変更

各関数の目的が若干違って, 結局別々の関数になってしまいました。
いかがでしょう？
__trim_optional_whitespaceは変更してしまいましたが, 元に戻しても良いと思います。

2022-06-10 12:38 UTC, ryojiroakiyama commented
trim関数をutilsに移動
OWSをクラス内定数に(timeとかみたいに)

2022-06-10 14:53 UTC, kohkubo commented on srcs/http/request/RequestInfo.hpp
> +    std::string                        first_;
pairのfirstとわかりにくいので、typeのほうがわかりやすいと思いましたがどうでしょう？

2022-06-10 15:21 UTC, ryojiroakiyama commented on srcs/http/request/RequestInfo.hpp
> +    std::string                        first_;
良いと思います！
助かります〜！

2022-06-12 05:44 UTC, nakamo326 approved these changes

2022-06-12 05:46 UTC, merged